// ----------------------------------------------------------------------------
// <auto-generated>
// 		This code was generated by a tool on 05/15/2017 22:57:46.
//
//		Changes to this file may cause incorrect behavior and will be
// 			list if the code is re-generated.
//
// Output files: AssemblyInfo.cs and the configured nuspec file
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Newbe.CQP.Framework.Tools.MSBuildTask")]
[assembly: AssemblyDescription("Newbe.CQP.Framework快速打包MSBuild扩展")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Newbe")]
[assembly: AssemblyProduct("Newbe.CQP.Framework.Tools.MSBuildTask")]
[assembly: AssemblyCopyright("Copyright Newbe2017")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("344a228b-0761-4b25-92b8-b4ebf5f19481")]

[assembly: AssemblyVersion("1.1.0")]
[assembly: AssemblyFileVersion("1.1.0")]

